apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-app-ingress-canary
  labels:
    app: voting-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: {{.Values.canaryWeight}}
spec:
  rules:
    - host: vote-app-chart
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: result-test
                port:
                  number: 80
          - path: /vote/*
            pathType: Prefix
            backend:
              service:
                name: vote-test
                port:
                  number: 80